//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationInfo() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ApplicationInfo", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Просмотр условий поступления.
        /// </summary>
        internal static string AppDetails {
            get {
                return ResourceManager.GetString("AppDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Для данного конкурса Вы можете указать приоритетность образовательных программ.
        /// </summary>
        internal static string AppInnerProirity {
            get {
                return ResourceManager.GetString("AppInnerProirity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вы отозвали это заявление.
        /// </summary>
        internal static string ApplicationCanceled {
            get {
                return ResourceManager.GetString("ApplicationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Редактировать заявление.
        /// </summary>
        internal static string ApplicationChange {
            get {
                return ResourceManager.GetString("ApplicationChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Удалить заявление целиком.
        /// </summary>
        internal static string ApplicationDelete {
            get {
                return ResourceManager.GetString("ApplicationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Основные сведения.
        /// </summary>
        internal static string ApplicationInfoHeader {
            get {
                return ResourceManager.GetString("ApplicationInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Изменить приоритеты.
        /// </summary>
        internal static string ApplicationPriorityChange {
            get {
                return ResourceManager.GetString("ApplicationPriorityChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Статус заявления:.
        /// </summary>
        internal static string AppStatus {
            get {
                return ResourceManager.GetString("AppStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Отозвать заявление.
        /// </summary>
        internal static string btnCancelApplication {
            get {
                return ResourceManager.GetString("btnCancelApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Сохранить изменения.
        /// </summary>
        internal static string btnSaveChanges {
            get {
                return ResourceManager.GetString("btnSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Отправить.
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Просмотреть письмо.
        /// </summary>
        internal static string btnViewMotivationalMail {
            get {
                return ResourceManager.GetString("btnViewMotivationalMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как &lt;h5&gt;Внимание!&lt;/h5&gt;
        ///    &lt;p&gt;Отзывая данное заявление, вы отказываетесь от участия в конкурсе на указанную образовательную программу.Восстановить данное заявление будет уже невозможно.&lt;/p&gt;
        ///    &lt;h4&gt;Вы хотите отказаться от участия в конкурсе?&lt;/h4&gt;.
        /// </summary>
        internal static string CancelAppMessage {
            get {
                return ResourceManager.GetString("CancelAppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Скачать заявление.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Название.
        /// </summary>
        internal static string ExamsName {
            get {
                return ResourceManager.GetString("ExamsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Состояние.
        /// </summary>
        internal static string ExamsStage {
            get {
                return ResourceManager.GetString("ExamsStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Пожалуйста, прикрепляйте общие для каждого заявления файлы (сканы паспорта / документа об образовании и т.п.) в раздел.
        /// </summary>
        internal static string FilesWarning1 {
            get {
                return ResourceManager.GetString("FilesWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как В данный раздел прикрепляйте подписанный бланк заявления.
        /// </summary>
        internal static string FilesWarning2 {
            get {
                return ResourceManager.GetString("FilesWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Добавить файл.
        /// </summary>
        internal static string HeaderAddFile {
            get {
                return ResourceManager.GetString("HeaderAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Основная информация.
        /// </summary>
        internal static string HeaderBaseInfo {
            get {
                return ResourceManager.GetString("HeaderBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Удалить.
        /// </summary>
        internal static string HeaderDelete {
            get {
                return ResourceManager.GetString("HeaderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Эссе.
        /// </summary>
        internal static string HeaderEssay {
            get {
                return ResourceManager.GetString("HeaderEssay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Экзамены.
        /// </summary>
        internal static string HeaderExams {
            get {
                return ResourceManager.GetString("HeaderExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Комментарии.
        /// </summary>
        internal static string HeaderFileComments {
            get {
                return ResourceManager.GetString("HeaderFileComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Имя файла.
        /// </summary>
        internal static string HeaderFilename {
            get {
                return ResourceManager.GetString("HeaderFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Размер.
        /// </summary>
        internal static string HeaderFilesize {
            get {
                return ResourceManager.GetString("HeaderFilesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Мотивационное письмо.
        /// </summary>
        internal static string HeaderMotivationalMail {
            get {
                return ResourceManager.GetString("HeaderMotivationalMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как В портфолио нет файлов.
        /// </summary>
        internal static string HeaderNoFiles {
            get {
                return ResourceManager.GetString("HeaderNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Портфолио.
        /// </summary>
        internal static string HeaderPortfolio {
            get {
                return ResourceManager.GetString("HeaderPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Главное меню.
        /// </summary>
        internal static string LinkMainMenu {
            get {
                return ResourceManager.GetString("LinkMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как &lt;/span&gt;&lt;b&gt;В мотивационном письме должны содержаться:&lt;/b&gt; 
        ///    &lt;ul&gt;
        ///        &lt;li&gt;необходимые сведения об опыте профессиональной подготовки/деятельности;&lt;/li&gt;
        ///        &lt;li&gt;сведения, подтверждающие необходимость получения знаний/навыков, освоение/приобретение которых возможно в период обучения на выбранной программе;&lt;/li&gt;
        ///        &lt;li&gt;перспективы/планы реализации полученных знаний/навыков в будущей профессиональной деятельности.&lt;/li&gt; 
        ///&lt;li&gt; Файл не должен содержать информацию, способствующую установлению авто [остаток строки был усечен]&quot;;.
        /// </summary>
        internal static string MotivationalMailInformation {
            get {
                return ResourceManager.GetString("MotivationalMailInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Мотивационное письмо.
        /// </summary>
        internal static string MotiveLetter {
            get {
                return ResourceManager.GetString("MotiveLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Подробно (на английском).
        /// </summary>
        internal static string MotiveLetterDetails {
            get {
                return ResourceManager.GetString("MotiveLetterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Образовательная программа.
        /// </summary>
        internal static string ObrazProgram {
            get {
                return ResourceManager.GetString("ObrazProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вам следует.
        /// </summary>
        internal static string PrintFormWarning1 {
            get {
                return ResourceManager.GetString("PrintFormWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как распечатать заявление&lt;/a&gt; и прийти с ним в приёмную комиссию.
        /// </summary>
        internal static string PrintFormWarning2 {
            get {
                return ResourceManager.GetString("PrintFormWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как &lt;abbr title=&quot;Наивысший приоритет равен 1&quot;&gt;Приоритет&lt;/abbr&gt;.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Направление.
        /// </summary>
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Профиль.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Подано.
        /// </summary>
        internal static string StatusActive {
            get {
                return ResourceManager.GetString("StatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Отозвано.
        /// </summary>
        internal static string StatusCancelled {
            get {
                return ResourceManager.GetString("StatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Форма обучения.
        /// </summary>
        internal static string StudyForm {
            get {
                return ResourceManager.GetString("StudyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Информация о заявлении.
        /// </summary>
        internal static string Subheader {
            get {
                return ResourceManager.GetString("Subheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Просмотр заявления.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Просмотр/Добавить файлы.
        /// </summary>
        internal static string ViewAddFiles {
            get {
                return ResourceManager.GetString("ViewAddFiles", resourceCulture);
            }
        }
    }
}
