//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ApplicationInfo", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application status:.
        /// </summary>
        internal static string AppStatus {
            get {
                return ResourceManager.GetString("AppStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw the application.
        /// </summary>
        internal static string btnCancelApplication {
            get {
                return ResourceManager.GetString("btnCancelApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string btnSaveChanges {
            get {
                return ResourceManager.GetString("btnSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the mail.
        /// </summary>
        internal static string btnViewMotivationalMail {
            get {
                return ResourceManager.GetString("btnViewMotivationalMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h5&gt;Внимание!&lt;/h5&gt;
        ///    &lt;p&gt;Отзывая данное заявление, вы отказываетесь от участия в конкурсе на указанную образовательную программу.Восстановить данное заявление будет уже невозможно.&lt;/p&gt;
        ///    &lt;h4&gt;Вы хотите отказаться от участия в конкурсе?&lt;/h4&gt;.
        /// </summary>
        internal static string CancelAppMessage {
            get {
                return ResourceManager.GetString("CancelAppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the application.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the file.
        /// </summary>
        internal static string HeaderAddFile {
            get {
                return ResourceManager.GetString("HeaderAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base info.
        /// </summary>
        internal static string HeaderBaseInfo {
            get {
                return ResourceManager.GetString("HeaderBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string HeaderDelete {
            get {
                return ResourceManager.GetString("HeaderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string HeaderFileComments {
            get {
                return ResourceManager.GetString("HeaderFileComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string HeaderFilename {
            get {
                return ResourceManager.GetString("HeaderFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string HeaderFilesize {
            get {
                return ResourceManager.GetString("HeaderFilesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivational mail.
        /// </summary>
        internal static string HeaderMotivationalMail {
            get {
                return ResourceManager.GetString("HeaderMotivationalMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files in portfilio.
        /// </summary>
        internal static string HeaderNoFiles {
            get {
                return ResourceManager.GetString("HeaderNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        internal static string HeaderPortfolio {
            get {
                return ResourceManager.GetString("HeaderPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/span&gt;&lt;b&gt;The motivational mail must contain:&lt;/b&gt; 
        ///    &lt;ul&gt;
        ///        &lt;li&gt;the necessary information about the experience of training / activity;&lt;/li&gt;
        ///        &lt;li&gt;information confirming the need for knowledge / skill development / acquisition of which is possible in the duration of the selected program;&lt;/li&gt;
        ///        &lt;li&gt;prospects / plans to implement the acquired knowledge / skills for future careers.&lt;/li&gt;
        ///    &lt;/ul&gt;&lt;span&gt;.
        /// </summary>
        internal static string MotivationalMailInformation {
            get {
                return ResourceManager.GetString("MotivationalMailInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational program.
        /// </summary>
        internal static string ObrazProgram {
            get {
                return ResourceManager.GetString("ObrazProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;abbr title=&quot;Наивысший приоритет равен 1&quot;&gt;Приоритет&lt;/abbr&gt;.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string StatusActive {
            get {
                return ResourceManager.GetString("StatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawn.
        /// </summary>
        internal static string StatusCancelled {
            get {
                return ResourceManager.GetString("StatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study form.
        /// </summary>
        internal static string StudyForm {
            get {
                return ResourceManager.GetString("StudyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application info.
        /// </summary>
        internal static string Subheader {
            get {
                return ResourceManager.GetString("Subheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View application.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
