//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EducationInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EducationInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EducationInfo", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регион (для российских аттестатов).
        /// </summary>
        internal static string AttestatRegion {
            get {
                return ResourceManager.GetString("AttestatRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите номер региона.
        /// </summary>
        internal static string AttestatRegion_Message {
            get {
                return ResourceManager.GetString("AttestatRegion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средний балл.
        /// </summary>
        internal static string AvgMark {
            get {
                return ResourceManager.GetString("AvgMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна, в которой получено предыдущее образование.
        /// </summary>
        internal static string CountryEducId {
            get {
                return ResourceManager.GetString("CountryEducId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        internal static string DiplomNumber {
            get {
                return ResourceManager.GetString("DiplomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите номер документа.
        /// </summary>
        internal static string DiplomNumber_Message {
            get {
                return ResourceManager.GetString("DiplomNumber_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серия.
        /// </summary>
        internal static string DiplomSeries {
            get {
                return ResourceManager.GetString("DiplomSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите серию документа.
        /// </summary>
        internal static string DiplomSeries_Message {
            get {
                return ResourceManager.GetString("DiplomSeries_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема дипломной работы.
        /// </summary>
        internal static string DiplomTheme {
            get {
                return ResourceManager.GetString("DiplomTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ об образовании.
        /// </summary>
        internal static string EducationDocumentHeader {
            get {
                return ResourceManager.GetString("EducationDocumentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите год в 4-значном формате.
        /// </summary>
        internal static string EducationInfo_SchoolExitYear_MessageFormat {
            get {
                return ResourceManager.GetString("EducationInfo_SchoolExitYear_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите название образовательного учреждения.
        /// </summary>
        internal static string EducationInfo_SchoolName_Message {
            get {
                return ResourceManager.GetString("EducationInfo_SchoolName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер свидетельства.
        /// </summary>
        internal static string EqualityDocumentNumber {
            get {
                return ResourceManager.GetString("EqualityDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имею сертификат ТРКИ.
        /// </summary>
        internal static string HasTRKI {
            get {
                return ResourceManager.GetString("HasTRKI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные о высшем образовании.
        /// </summary>
        internal static string HEDataHeader {
            get {
                return ResourceManager.GetString("HEDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год начала обучения.
        /// </summary>
        internal static string HEEntryYear {
            get {
                return ResourceManager.GetString("HEEntryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свидетельство об эквивалентности.
        /// </summary>
        internal static string IsEqual {
            get {
                return ResourceManager.GetString("IsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иностранный язык.
        /// </summary>
        internal static string LanguageId {
            get {
                return ResourceManager.GetString("LanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квалификация.
        /// </summary>
        internal static string PersonQualification {
            get {
                return ResourceManager.GetString("PersonQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление (специальность).
        /// </summary>
        internal static string PersonSpecialization {
            get {
                return ResourceManager.GetString("PersonSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма обучения.
        /// </summary>
        internal static string PersonStudyForm {
            get {
                return ResourceManager.GetString("PersonStudyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите регион.
        /// </summary>
        internal static string RegionEducId {
            get {
                return ResourceManager.GetString("RegionEducId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес школы.
        /// </summary>
        internal static string SchoolAddress {
            get {
                return ResourceManager.GetString("SchoolAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оконченный класс.
        /// </summary>
        internal static string SchoolExitClass {
            get {
                return ResourceManager.GetString("SchoolExitClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год окончания обучения.
        /// </summary>
        internal static string SchoolExitYear {
            get {
                return ResourceManager.GetString("SchoolExitYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите год окончания обучения.
        /// </summary>
        internal static string SchoolExitYear_Message {
            get {
                return ResourceManager.GetString("SchoolExitYear_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название образовательного учреждения.
        /// </summary>
        internal static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип образовательного учреждения.
        /// </summary>
        internal static string SchoolTypeId {
            get {
                return ResourceManager.GetString("SchoolTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер сертификата ТРКИ.
        /// </summary>
        internal static string TRKICertificateNumber {
            get {
                return ResourceManager.GetString("TRKICertificateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите тип поступления.
        /// </summary>
        internal static string VuzAdditionalTypeId {
            get {
                return ResourceManager.GetString("VuzAdditionalTypeId", resourceCulture);
            }
        }
    }
}
