//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NewApplication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewApplication() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.NewApplication", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry is closed.
        /// </summary>
        internal static string AG_PriemClosed {
            get {
                return ResourceManager.GetString("AG_PriemClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an application.
        /// </summary>
        internal static string btnCreateApp {
            get {
                return ResourceManager.GetString("btnCreateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need hostel during education period.
        /// </summary>
        internal static string chbNeedHostel {
            get {
                return ResourceManager.GetString("chbNeedHostel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has already applied.
        /// </summary>
        internal static string ErrorHasApplication {
            get {
                return ResourceManager.GetString("ErrorHasApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the faculty.
        /// </summary>
        internal static string HeaderFaculty {
            get {
                return ResourceManager.GetString("HeaderFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are entering on the .
        /// </summary>
        internal static string HeaderFirstCourse_1 {
            get {
                return ResourceManager.GetString("HeaderFirstCourse_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first course.
        /// </summary>
        internal static string HeaderFirstCourse_2 {
            get {
                return ResourceManager.GetString("HeaderFirstCourse_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the study program.
        /// </summary>
        internal static string HeaderObrazProgram {
            get {
                return ResourceManager.GetString("HeaderObrazProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your obtaining level:.
        /// </summary>
        internal static string HeaderObtainingLevel {
            get {
                return ResourceManager.GetString("HeaderObtainingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the profession.
        /// </summary>
        internal static string HeaderProfession {
            get {
                return ResourceManager.GetString("HeaderProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the profile.
        /// </summary>
        internal static string HeaderProfile {
            get {
                return ResourceManager.GetString("HeaderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel education.
        /// </summary>
        internal static string IsParallel {
            get {
                return ResourceManager.GetString("IsParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second higher education.
        /// </summary>
        internal static string IsReduced {
            get {
                return ResourceManager.GetString("IsReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the persons with higher education.
        /// </summary>
        internal static string IsSecond {
            get {
                return ResourceManager.GetString("IsSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неоднозначный выбор учебного плана.
        /// </summary>
        internal static string NewApp_2MoreEntry {
            get {
                return ResourceManager.GetString("NewApp_2MoreEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приём заявлений на данное направление закрыт..
        /// </summary>
        internal static string NewApp_ClosedEntry {
            get {
                return ResourceManager.GetString("NewApp_ClosedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при удалении заявления.
        /// </summary>
        internal static string NewApp_DeleteApp_Fail {
            get {
                return ResourceManager.GetString("NewApp_DeleteApp_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя удалить уже подтверждённое заявление!.
        /// </summary>
        internal static string NewApp_FailDeleteApp_IsCommited {
            get {
                return ResourceManager.GetString("NewApp_FailDeleteApp_IsCommited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление на данную программу уже подано.
        /// </summary>
        internal static string NewApp_HasApplicationOnEntry {
            get {
                return ResourceManager.GetString("NewApp_HasApplicationOnEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден учебный план.
        /// </summary>
        internal static string NewApp_NoEntry {
            get {
                return ResourceManager.GetString("NewApp_NoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет доступных направлений для подачи заявления.
        /// </summary>
        internal static string NewApp_NoFreeEntries {
            get {
                return ResourceManager.GetString("NewApp_NoFreeEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приём заявлений на данное направление ещё не открыт..
        /// </summary>
        internal static string NewApp_NotOpenedEntry {
            get {
                return ResourceManager.GetString("NewApp_NotOpenedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Application.
        /// </summary>
        internal static string PageSubheader {
            get {
                return ResourceManager.GetString("PageSubheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new application.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor/Specialist.
        /// </summary>
        internal static string Select_FirstCourse {
            get {
                return ResourceManager.GetString("Select_FirstCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magistery.
        /// </summary>
        internal static string Select_Magistery {
            get {
                return ResourceManager.GetString("Select_Magistery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget places.
        /// </summary>
        internal static string Select_StudyBasis1 {
            get {
                return ResourceManager.GetString("Select_StudyBasis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string Select_StudyBasis2 {
            get {
                return ResourceManager.GetString("Select_StudyBasis2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-Time.
        /// </summary>
        internal static string Select_StudyForm1 {
            get {
                return ResourceManager.GetString("Select_StudyForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part-Time.
        /// </summary>
        internal static string Select_StudyForm2 {
            get {
                return ResourceManager.GetString("Select_StudyForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select study basis.
        /// </summary>
        internal static string StudyBasis {
            get {
                return ResourceManager.GetString("StudyBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select study form.
        /// </summary>
        internal static string StudyForm {
            get {
                return ResourceManager.GetString("StudyForm", resourceCulture);
            }
        }
    }
}
