//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NewApplication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewApplication() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.NewApplication", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Entry is closed.
        /// </summary>
        internal static string AG_PriemClosed {
            get {
                return ResourceManager.GetString("AG_PriemClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Направление.
        /// </summary>
        internal static string BlockData_LicenseProgram {
            get {
                return ResourceManager.GetString("BlockData_LicenseProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Образовательная программа.
        /// </summary>
        internal static string BlockData_ObrazProgram {
            get {
                return ResourceManager.GetString("BlockData_ObrazProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Специализация.
        /// </summary>
        internal static string BlockData_Specialization {
            get {
                return ResourceManager.GetString("BlockData_Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Основа обучения.
        /// </summary>
        internal static string BlockData_StudyBasis {
            get {
                return ResourceManager.GetString("BlockData_StudyBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Форма обучения.
        /// </summary>
        internal static string BlockData_StudyForm {
            get {
                return ResourceManager.GetString("BlockData_StudyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Create an application.
        /// </summary>
        internal static string btnCreateApp {
            get {
                return ResourceManager.GetString("btnCreateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как I need hostel during education period.
        /// </summary>
        internal static string chbNeedHostel {
            get {
                return ResourceManager.GetString("chbNeedHostel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как The application has already applied.
        /// </summary>
        internal static string ErrorHasApplication {
            get {
                return ResourceManager.GetString("ErrorHasApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Select the faculty.
        /// </summary>
        internal static string HeaderFaculty {
            get {
                return ResourceManager.GetString("HeaderFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как You are entering on the .
        /// </summary>
        internal static string HeaderFirstCourse_1 {
            get {
                return ResourceManager.GetString("HeaderFirstCourse_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как first course.
        /// </summary>
        internal static string HeaderFirstCourse_2 {
            get {
                return ResourceManager.GetString("HeaderFirstCourse_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Select the study program.
        /// </summary>
        internal static string HeaderObrazProgram {
            get {
                return ResourceManager.GetString("HeaderObrazProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Your obtaining level:.
        /// </summary>
        internal static string HeaderObtainingLevel {
            get {
                return ResourceManager.GetString("HeaderObtainingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Select the profession.
        /// </summary>
        internal static string HeaderProfession {
            get {
                return ResourceManager.GetString("HeaderProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Select the profile.
        /// </summary>
        internal static string HeaderProfile {
            get {
                return ResourceManager.GetString("HeaderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Parallel education.
        /// </summary>
        internal static string IsParallel {
            get {
                return ResourceManager.GetString("IsParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Second higher education.
        /// </summary>
        internal static string IsReduced {
            get {
                return ResourceManager.GetString("IsReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как For the persons with higher education.
        /// </summary>
        internal static string IsSecond {
            get {
                return ResourceManager.GetString("IsSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Неоднозначный выбор учебного плана.
        /// </summary>
        internal static string NewApp_2MoreEntry {
            get {
                return ResourceManager.GetString("NewApp_2MoreEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Приём заявлений на данное направление закрыт..
        /// </summary>
        internal static string NewApp_ClosedEntry {
            get {
                return ResourceManager.GetString("NewApp_ClosedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Ошибка при удалении заявления.
        /// </summary>
        internal static string NewApp_DeleteApp_Fail {
            get {
                return ResourceManager.GetString("NewApp_DeleteApp_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Нельзя удалить уже подтверждённое заявление!.
        /// </summary>
        internal static string NewApp_FailDeleteApp_IsCommited {
            get {
                return ResourceManager.GetString("NewApp_FailDeleteApp_IsCommited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Заявление на данную программу уже подано.
        /// </summary>
        internal static string NewApp_HasApplicationOnEntry {
            get {
                return ResourceManager.GetString("NewApp_HasApplicationOnEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Не найден учебный план.
        /// </summary>
        internal static string NewApp_NoEntry {
            get {
                return ResourceManager.GetString("NewApp_NoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Нет доступных направлений для подачи заявления.
        /// </summary>
        internal static string NewApp_NoFreeEntries {
            get {
                return ResourceManager.GetString("NewApp_NoFreeEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Приём заявлений на данное направление ещё не открыт..
        /// </summary>
        internal static string NewApp_NotOpenedEntry {
            get {
                return ResourceManager.GetString("NewApp_NotOpenedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как New Application.
        /// </summary>
        internal static string PageSubheader {
            get {
                return ResourceManager.GetString("PageSubheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Create a new application.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Bachelor/Specialist.
        /// </summary>
        internal static string Select_FirstCourse {
            get {
                return ResourceManager.GetString("Select_FirstCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Magistery.
        /// </summary>
        internal static string Select_Magistery {
            get {
                return ResourceManager.GetString("Select_Magistery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Budget places.
        /// </summary>
        internal static string Select_StudyBasis1 {
            get {
                return ResourceManager.GetString("Select_StudyBasis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Paid.
        /// </summary>
        internal static string Select_StudyBasis2 {
            get {
                return ResourceManager.GetString("Select_StudyBasis2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Full-Time.
        /// </summary>
        internal static string Select_StudyForm1 {
            get {
                return ResourceManager.GetString("Select_StudyForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Part-Time.
        /// </summary>
        internal static string Select_StudyForm2 {
            get {
                return ResourceManager.GetString("Select_StudyForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Select study basis.
        /// </summary>
        internal static string StudyBasis {
            get {
                return ResourceManager.GetString("StudyBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Select study form.
        /// </summary>
        internal static string StudyForm {
            get {
                return ResourceManager.GetString("StudyForm", resourceCulture);
            }
        }
    }
}
