//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PassportInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PassportInfo() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PassportInfo", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Паспорт.
        /// </summary>
        internal static string HeaderPassport {
            get {
                return ResourceManager.GetString("HeaderPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Слишком длинное значение.
        /// </summary>
        internal static string LongValue_Message {
            get {
                return ResourceManager.GetString("LongValue_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Кем выдан.
        /// </summary>
        internal static string PassportAuthor {
            get {
                return ResourceManager.GetString("PassportAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Код подразделения.
        /// </summary>
        internal static string PassportCode {
            get {
                return ResourceManager.GetString("PassportCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Дата выдачи.
        /// </summary>
        internal static string PassportDate {
            get {
                return ResourceManager.GetString("PassportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите, кем выдан паспорт.
        /// </summary>
        internal static string PassportInfo_PassportAuthor_Message {
            get {
                return ResourceManager.GetString("PassportInfo_PassportAuthor_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите дату выдачи паспорта.
        /// </summary>
        internal static string PassportInfo_PassportDate_Message {
            get {
                return ResourceManager.GetString("PassportInfo_PassportDate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите номер паспорта.
        /// </summary>
        internal static string PassportInfo_PassportNumber_Message {
            get {
                return ResourceManager.GetString("PassportInfo_PassportNumber_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите серию паспорта.
        /// </summary>
        internal static string PassportInfo_PassportSeries_Message {
            get {
                return ResourceManager.GetString("PassportInfo_PassportSeries_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Номер.
        /// </summary>
        internal static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Серия.
        /// </summary>
        internal static string PassportSeries {
            get {
                return ResourceManager.GetString("PassportSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Тип.
        /// </summary>
        internal static string PassportType {
            get {
                return ResourceManager.GetString("PassportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Номер паспорта РФ должен состоять из 6 цифр без пробелов.
        /// </summary>
        internal static string RF_Number_Message {
            get {
                return ResourceManager.GetString("RF_Number_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Серия паспорта РФ должна состоять из 4 цифр без пробелов.
        /// </summary>
        internal static string RF_Series_Message {
            get {
                return ResourceManager.GetString("RF_Series_Message", resourceCulture);
            }
        }
    }
}
