//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PersonalOfficeForeign {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonalOfficeForeign() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PersonalOfficeForeign", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AddressMessage {
            get {
                return ResourceManager.GetString("AddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with this conditions.
        /// </summary>
        internal static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of  birth.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BirthDateMessage {
            get {
                return ResourceManager.GetString("BirthDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of birth.
        /// </summary>
        internal static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BirthPlaceMessage {
            get {
                return ResourceManager.GetString("BirthPlaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your address.
        /// </summary>
        internal static string HeaderAddress {
            get {
                return ResourceManager.GetString("HeaderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education (name, place, dates of entering and graduation):.
        /// </summary>
        internal static string HeaderEducation {
            get {
                return ResourceManager.GetString("HeaderEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What languages do you know? What is the level of your knowledge of the foreign languages?.
        /// </summary>
        internal static string HeaderForeignLanguages {
            get {
                return ResourceManager.GetString("HeaderForeignLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your job (occupation) or place of study at the moment of application.
        /// </summary>
        internal static string HeaderJob {
            get {
                return ResourceManager.GetString("HeaderJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National passport for entering the Russian Federation.
        /// </summary>
        internal static string HeaderPassport {
            get {
                return ResourceManager.GetString("HeaderPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Informaion.
        /// </summary>
        internal static string HeaderPersonalInformation {
            get {
                return ResourceManager.GetString("HeaderPersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important: I declare that the information given on this form is correct. I’m informed about the requirements for a candidate to study in the Russian Federation and for the documents, as well as the terms of staying in the Russian Federation. I give my consent to processing the information provided on this form..
        /// </summary>
        internal static string HeaderPrivacyTerms {
            get {
                return ResourceManager.GetString("HeaderPrivacyTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which embassy or consulate of the Russian Federation abroad processes your visa?.
        /// </summary>
        internal static string HeaderVisa {
            get {
                return ResourceManager.GetString("HeaderVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name, father’s name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NameMessage {
            get {
                return ResourceManager.GetString("NameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizenship.
        /// </summary>
        internal static string NationalityId {
            get {
                return ResourceManager.GetString("NationalityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What level of education do you want to obtain in SPbSU?.
        /// </summary>
        internal static string ObtainingLevelId {
            get {
                return ResourceManager.GetString("ObtainingLevelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of issue.
        /// </summary>
        internal static string PassportDate {
            get {
                return ResourceManager.GetString("PassportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PassportDateMessage {
            get {
                return ResourceManager.GetString("PassportDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of expire.
        /// </summary>
        internal static string PassportExpire {
            get {
                return ResourceManager.GetString("PassportExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PassportExpireMessage {
            get {
                return ResourceManager.GetString("PassportExpireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PassportNumberMessage {
            get {
                return ResourceManager.GetString("PassportNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        internal static string PassportSeries {
            get {
                return ResourceManager.GetString("PassportSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number (in Russia).
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PhoneMessage {
            get {
                return ResourceManager.GetString("PhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string SexFemale {
            get {
                return ResourceManager.GetString("SexFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string SexMale {
            get {
                return ResourceManager.GetString("SexMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of finishing/graduation.
        /// </summary>
        internal static string StudyFinish {
            get {
                return ResourceManager.GetString("StudyFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StudyFinishMessage {
            get {
                return ResourceManager.GetString("StudyFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What level of education have you got?.
        /// </summary>
        internal static string StudyLevelId {
            get {
                return ResourceManager.GetString("StudyLevelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name, place.
        /// </summary>
        internal static string StudyPlace {
            get {
                return ResourceManager.GetString("StudyPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StudyPlaceMessage {
            get {
                return ResourceManager.GetString("StudyPlaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of entering.
        /// </summary>
        internal static string StudyStart {
            get {
                return ResourceManager.GetString("StudyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StudyStartMessage {
            get {
                return ResourceManager.GetString("StudyStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name/Surname (as in your passport).
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your surname.
        /// </summary>
        internal static string SurnameMessage {
            get {
                return ResourceManager.GetString("SurnameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Country.
        /// </summary>
        internal static string VisaCountryName {
            get {
                return ResourceManager.GetString("VisaCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VisaCountryNameMessage {
            get {
                return ResourceManager.GetString("VisaCountryNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal address.
        /// </summary>
        internal static string VisaPostAddress {
            get {
                return ResourceManager.GetString("VisaPostAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VisaPostAddressMessage {
            get {
                return ResourceManager.GetString("VisaPostAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town/City.
        /// </summary>
        internal static string VisaTownName {
            get {
                return ResourceManager.GetString("VisaTownName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VisaTownNameMessage {
            get {
                return ResourceManager.GetString("VisaTownNameMessage", resourceCulture);
            }
        }
    }
}
