//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PersonalOfficeForeign {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonalOfficeForeign() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PersonalOfficeForeign", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Permanent address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string AddressMessage {
            get {
                return ResourceManager.GetString("AddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как I agree with this conditions.
        /// </summary>
        internal static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Date of  birth.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string BirthDateMessage {
            get {
                return ResourceManager.GetString("BirthDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Place of birth.
        /// </summary>
        internal static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string BirthPlaceMessage {
            get {
                return ResourceManager.GetString("BirthPlaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Your address.
        /// </summary>
        internal static string HeaderAddress {
            get {
                return ResourceManager.GetString("HeaderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Education (name, place, dates of entering and graduation):.
        /// </summary>
        internal static string HeaderEducation {
            get {
                return ResourceManager.GetString("HeaderEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как What languages do you know? What is the level of your knowledge of the foreign languages?.
        /// </summary>
        internal static string HeaderForeignLanguages {
            get {
                return ResourceManager.GetString("HeaderForeignLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Your job (occupation) or place of study at the moment of application.
        /// </summary>
        internal static string HeaderJob {
            get {
                return ResourceManager.GetString("HeaderJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как National passport for entering the Russian Federation.
        /// </summary>
        internal static string HeaderPassport {
            get {
                return ResourceManager.GetString("HeaderPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Personal Informaion.
        /// </summary>
        internal static string HeaderPersonalInformation {
            get {
                return ResourceManager.GetString("HeaderPersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Important: I declare that the information given on this form is correct. I’m informed about the requirements for a candidate to study in the Russian Federation and for the documents, as well as the terms of staying in the Russian Federation. I give my consent to processing the information provided on this form..
        /// </summary>
        internal static string HeaderPrivacyTerms {
            get {
                return ResourceManager.GetString("HeaderPrivacyTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Which embassy or consulate of the Russian Federation abroad processes your visa?.
        /// </summary>
        internal static string HeaderVisa {
            get {
                return ResourceManager.GetString("HeaderVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Name, father’s name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string NameMessage {
            get {
                return ResourceManager.GetString("NameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Citizenship.
        /// </summary>
        internal static string NationalityId {
            get {
                return ResourceManager.GetString("NationalityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как What level of education do you want to obtain in SPbSU?.
        /// </summary>
        internal static string ObtainingLevelId {
            get {
                return ResourceManager.GetString("ObtainingLevelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Date of issue.
        /// </summary>
        internal static string PassportDate {
            get {
                return ResourceManager.GetString("PassportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string PassportDateMessage {
            get {
                return ResourceManager.GetString("PassportDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Date of expire.
        /// </summary>
        internal static string PassportExpire {
            get {
                return ResourceManager.GetString("PassportExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string PassportExpireMessage {
            get {
                return ResourceManager.GetString("PassportExpireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Number.
        /// </summary>
        internal static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string PassportNumberMessage {
            get {
                return ResourceManager.GetString("PassportNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Series.
        /// </summary>
        internal static string PassportSeries {
            get {
                return ResourceManager.GetString("PassportSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Phone number (in Russia).
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string PhoneMessage {
            get {
                return ResourceManager.GetString("PhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Sex.
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Female.
        /// </summary>
        internal static string SexFemale {
            get {
                return ResourceManager.GetString("SexFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Male.
        /// </summary>
        internal static string SexMale {
            get {
                return ResourceManager.GetString("SexMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Date of finishing/graduation.
        /// </summary>
        internal static string StudyFinish {
            get {
                return ResourceManager.GetString("StudyFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string StudyFinishMessage {
            get {
                return ResourceManager.GetString("StudyFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как What level of education have you got?.
        /// </summary>
        internal static string StudyLevelId {
            get {
                return ResourceManager.GetString("StudyLevelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Name, place.
        /// </summary>
        internal static string StudyPlace {
            get {
                return ResourceManager.GetString("StudyPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string StudyPlaceMessage {
            get {
                return ResourceManager.GetString("StudyPlaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Date of entering.
        /// </summary>
        internal static string StudyStart {
            get {
                return ResourceManager.GetString("StudyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string StudyStartMessage {
            get {
                return ResourceManager.GetString("StudyStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Family name/Surname (as in your passport).
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Please, enter your surname.
        /// </summary>
        internal static string SurnameMessage {
            get {
                return ResourceManager.GetString("SurnameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как State/Country.
        /// </summary>
        internal static string VisaCountryName {
            get {
                return ResourceManager.GetString("VisaCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string VisaCountryNameMessage {
            get {
                return ResourceManager.GetString("VisaCountryNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Postal address.
        /// </summary>
        internal static string VisaPostAddress {
            get {
                return ResourceManager.GetString("VisaPostAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string VisaPostAddressMessage {
            get {
                return ResourceManager.GetString("VisaPostAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Town/City.
        /// </summary>
        internal static string VisaTownName {
            get {
                return ResourceManager.GetString("VisaTownName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string VisaTownNameMessage {
            get {
                return ResourceManager.GetString("VisaTownNameMessage", resourceCulture);
            }
        }
    }
}
